timezone: Europe/London
encoding: UTF-8

markdown: redcarpet
redcarpet:
  extensions: [ 'autolinks', 'smart', 'no_intra_emphasis', 'superscript' ]

permalink: /articles/:title/

url: http://woss.name
name: Notes from a Messy Desk
description: |
  This is where I (Graeme Mathieson, often known online as
  [@mathie](https://twitter.com/mathie)) write the occasional article about
  whatever interests me this week. The latest article will always be on the
  [home page](/), but you could always peruse [previous articles](/articles/)
  too.

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: post
    values:
      layout: post

exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# GitHub-enforced defaults
highlighter: pygments
safe: true
lsi: false
