name: Notes from a Messy Desk
description: The original net.presence of Graeme Mathieson (aka @mathie)
timezone: Europe/London

pygments: true
lsi: false

permalink: /:year/:month/:day/:title/

# Only show a maximum of 4 posts in a page. Works reasonably well so far with
# the volume of posts I produce these days.
paginate: 4

exclude:
  - Gemfile*
  - Rakefile
  - Procfile
  - README.md
