# Site settings
title: Notes from a Messy Desk
email: mathie@woss.name
description: > # this means to ignore newlines until "baseurl:"
  This is where I (Graeme Mathieson, often known online as @mathie) write the
  occasional article about whatever interests me this week.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://woss.name"
twitter_username: mathie
github_username:  mathie
timezone: London

# Build settings
markdown: redcarpet
highlighter: pygments

# GitHub mandated settings
safe: true
lsi: false

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "draft"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "default"
