# Site settings
title: Notes from a Messy Desk
email: mathie@woss.name
description: > # this means to ignore newlines until "baseurl:"
  This is where I (Graeme Mathieson, often known online as @mathie) write the
  occasional article about whatever interests me this week.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://woss.name"
twitter_username: mathie
github_username:  mathie

# Build settings
markdown: kramdown
